### ISSUE TITLE
OneToOne Mapping Testcase behaviour 

### ISSUE THREAD

**Issue by deepaksorthiya** [vladmihalcea/high-performance-java-persistence#102]
Hello @vladmihalcea , I was running testcase `BidirectionalOneToOneMapsIdTest#testLifecycle()` 
on  file [BidirectionalOneToOneMapsIdTest](https://github.com/vladmihalcea/high-performance-java-persistence/blob/5bd5b6702cbfd3d109c422dfd4307560e05f8b09/core/src/test/java/com/vladmihalcea/hpjp/hibernate/association/BidirectionalOneToOneMapsIdTest.java#L25) on master branch .  
Its not executing delete query for second Persistence Context and showing warning log 

`2024-10-31 11:39:19,727 WARN  [Alice]: o.h.p.e.AbstractEntityPersister - HHH000502: The [post] property of the [com.vladmihalcea.hpjp.hibernate.association.BidirectionalOneToOneMapsIdTest$PostDetails] entity was modified, but it won't be updated because the property is immutable.
` . 

 Is this behaviour is correct for this testcase?

**Comment by vladmihalcea** [comment]
The behavior is correct since the association is mandatory.

**Comment by deepaksorthiya** [comment]
@vladmihalcea Alright. Thanks for the quick reply.

**Comment by vladmihalcea** [comment]
You're welcome. By the way, how come you are testing this repo? Where did you learn about it?

**Comment by deepaksorthiya** [comment]
I am learning from your site [https://vladmihalcea.com/tutorials/hibernate/](https://vladmihalcea.com/tutorials/hibernate/).  It's managed beautifully and the best site for hibernate tutorial. Hats off to your hardwork.

**Comment by vladmihalcea** [comment]
Enjoy learning about it. There's also a public training you could join if you want to learn even more.
