### ISSUE TITLE
Set<Long> myfield is mapped as Set<Integer>

### ISSUE THREAD

**Issue by zhouchong90** [vladmihalcea/high-performance-java-persistence#13]
I have a class that contains a field with type `List<Long> myfield`
It maps to MySQL 5.7 as a json column. But when I read it out from Spring Data JPA, it becomes `Set<Integer>`, and had type cast errors when using it downstream. Please help..

**Comment by vladmihalcea** [comment]
Hibernate does not support JSON types natively, so it's up to you [how to define the custom JSON type](https://vladmihalcea.com/2016/06/20/how-to-map-json-objects-using-generic-hibernate-types/). In my example, I've been saving Java or `JsonNode` objects to JSON columns, not JSON arrays or maps.
