### ISSUE TITLE
The ebook from leanpub.com is impossible to buy from Russia

### ISSUE THREAD

**Issue by stIncMale** [vladmihalcea/high-performance-java-persistence#14]
This is probably not the best place to describe an issue, but I haven't found a better one.

The ebook is only available via leanpub.com. This site uses only PayPal to process payments, and it is impossible to pay via PayPal from Russia:

http://help.leanpub.com/reader-help/im-having-a-problem-using-a-credit-card-from-russian-federation-help

https://groups.google.com/forum/#!topic/leanpub/EMVVGa9D6C4

Would you please consider additionally selling an electronic version of the book via another online store? I know that a print version is available on Amazon, but I really do not want to buy the printed one.

**Comment by vladmihalcea** [comment]
I'm not aware of any other payment option which wouldn't require some monthly subscription from my part (e.g. Gumroad). In to years, this is the first time I hear about this kind of issue. Previously, there were two readers from India that had some problems, but they managed to get it working via their banks.

Now, although PayPal or Leanpub will probably fix their issues related to payments from Russia, I propose one of the following deals.

1. If you manage to send money from your PayPal to some other PayPal account which does not involve any banking, I can send you a free coupon for my book after you make the payment. This works if you already have a positive balance on PayPal, I guess.

2. If you buy the print book from Amazon and show me the receipt, I'll send you the ebook for free.

    The book is available on all supported Amazon sites, the one in [Amazon Italy is the cheapest now](https://www.amazon.com/High-Performance-Java-Persistence-Vlad-Mihalcea/dp/973022823X/), but I'm not sure which one you should use for shipping to Russia.

**Comment by stIncMale** [comment]
@vladmihalcea Thanks for the quick reply! The second option is good for me.

I have just ordered a printed copy from Amazon. Your email is not publicly available, so here is a publicly available (no sign in required) Google Drive link to three screenshots with my order details (1 from email, and 2 from Amazon website): https://drive.google.com/drive/folders/1vMNNB2EIGInZsDlBqa4pSzfAlR5Afzo9?usp=sharing

Could you please send the book (PDF) to the email shown in the top right corner on email-order-details.png image available via the link above (the same email is available [here](https://sites.google.com/site/aboutmale/contacts))? If you need additional information to confirm the order, please let me know (it would probably be better to do via the email).

**Comment by vladmihalcea** [comment]
@stIncMale I sent you the 100% discount URL over email. Enjoy reading it.

**Comment by stIncMale** [comment]
@vladmihalcea The discount URL worked perfectly. Thank you!

**Comment by vladmihalcea** [comment]
Enjoy reading it and looking forward to getting your feedback.
