### ISSUE TITLE
Issue with serialization

### ISSUE THREAD

**Issue by iLavryk** [vladmihalcea/high-performance-java-persistence#16]
There is a method 
static <T> T clone(T value)
in class JacksonUtil
which try to determine what type of deep copy use and in case if input Object implements Serializable interface it try to use java Serialization mechanism to copy object. But what if i use ArrayList<MyObject>  to store it to DB and MyObject is not implements it. Why just for all cases not use json serialization?
Can you do it preferable may be. Because it always fails with exception and force me to mark my Object as Serializable. But it is not what i want

**Comment by vladmihalcea** [comment]
This repository is just a playing ground for JPA and Hibernate.

If you are asking about JSON Types, then check out  [hibernate-types](https://github.com/vladmihalcea/hibernate-type). It might already do what you are asking.
