### ISSUE TITLE
Need Instruction of Maven Configurations for downloading Oracle JDBC driver

### ISSUE THREAD

**Issue by mingqin1** [vladmihalcea/high-performance-java-persistence#17]
Vlad:
  When running command "mvn clean test-compile",   I got maven errors about failure to download Oracle JDBC Driver.

  Here is the link -https://blogs.oracle.com/dev2dev/get-oracle-jdbc-drivers-and-ucp-from-oracle-maven-repository-without-ides

   In above post,  setting-security.xml  element should be  settings**S**ecurity rather than settingssecurity

**Comment by vladmihalcea** [comment]
Thanks for the tip.

I changed the scope of the [Oracle JDBC Driver](https://github.com/vladmihalcea/high-performance-java-persistence/blob/master/pom.xml#L171) to `provided` for the core. It's still needed by the jooq-oracle module.

As for how to install it, it's already documented in the [ReadMe Guide](https://github.com/vladmihalcea/high-performance-java-persistence/blob/master/README.md).
