### ISSUE TITLE
URL link is broken inside Readme.md -MySQL section "here" link  in sentense "Exact instructions can be found in here." 

### ISSUE THREAD

**Issue by mingqin1** [vladmihalcea/high-performance-java-persistence#18]
The here link is pointed to https://github.com/ursjoss/high-performance-java-persistence/blob/tb_mysql_instructions/MYSQL.md , which leads to 404 error

The correct link might be https://github.com/vladmihalcea/high-performance-java-persistence/blob/master/MYSQL.md

**Comment by ursjoss** [comment]
The correct link can be found in print #9

**Comment by ursjoss** [comment]
For those interested: https://github.com/ursjoss/high-performance-java-persistence/commit/88373dc7c2080d02e2e3965afae961495e7d956b

**Comment by ursjoss** [comment]
In my fork,  I am trying to keep up with Vlad's changes in an eclipse friendly way (branch [tb_eclipse]
 (https://github.com/ursjoss/high-performance-java-persistence/tree/tb_eclipse)). At least when not on holiday w/o laptop, as just now... 😎

**Comment by vladmihalcea** [comment]
Fixed. Thanks for pointing it out.

**Comment by ursjoss** [comment]
Oops, sorry for the noise...  I was mislead by the first part of the link 🤔
