### ISSUE TITLE
MariaDB Sequence Identifier Test-GlobalIdentifierGeneratorScopeTest.java 

### ISSUE THREAD

**Issue by mingqin1** [vladmihalcea/high-performance-java-persistence#19]
Hi Vlad:
      In your book( High-Performance-java-persistence) page 170,  9.2.3.2 Sequence Generator and 9.2.3. Numerical Identifiers, which imply MYSQL 5.7 doesn't support Sequence Generator.  MariaDB  10.3 starts support for CREATE SEQUENCE ( https://mariadb.com/kb/en/library/create-sequence/).

   I would like to use GlobalIdentifierGeneratorScopeTest.java  as template to test MariaDB 10.3 and hibernate sequence generator feature.
 
   Is the GlobalIdentifierGeneratorScopeTest.java intended for testing PostgreSQL and hibernate sequence generator?

Thanks
Ming Qin

**Comment by vladmihalcea** [comment]
You can use any test for MariaDB as well. This particular test was just for global seqeunce declarations so better use the [`PooledSequenceIdentifierTest`](https://github.com/vladmihalcea/high-performance-java-persistence/blob/147c1aef2120818ee0cd24729792a7637c3553b6/core/src/test/java/com/vladmihalcea/book/hpjp/hibernate/identifier/PooledSequenceIdentifierTest.java).
