### ISSUE TITLE
Json type doesn't supports generic type

### ISSUE THREAD

**Issue by quaff** [vladmihalcea/high-performance-java-persistence#2]
[https://vladmihalcea.com/2016/06/20/how-to-map-json-objects-using-generic-hibernate-types/](url)
`@Type(type = "json")
    @Column(columnDefinition = "json")
    private Location location;`
works fine.
`@Type(type = "json")
    @Column(columnDefinition = "json")
    private List<Location> locations;` will failed.
`( (ParameterType) parameters.get( PARAMETER_TYPE ) ).getReturnedClass()` should return ParameterizedType instead of Class.
Maybe AttributeConverter is a better solution.

**Comment by vladmihalcea** [comment]
It's intended to be like that because PostgreSQL and MySQL allow you to save a single root JSON object. Mapping a list of JSON objects is not, therefore, supported.
