### ISSUE TITLE
Oracle schema or MSSQL Schema?

### ISSUE THREAD

**Issue by lukaseder** [vladmihalcea/high-performance-java-persistence#20]
There's a file in your repository that references both the Oracle and MS SQL dialects:
https://github.com/vladmihalcea/high-performance-java-persistence/blob/master/jooq/jooq-mssql/src/test/resources/oracle/initial_schema.sql

From the contents, I suspect it is MS SQL, as Oracle doesn't have `BIGINT` or `DATETIME2` types... This looks more like Oracle syntax: https://github.com/vladmihalcea/high-performance-java-persistence/blob/master/jooq/jooq-oracle/src/test/resources/oracle/initial_schema.sql

**Comment by vladmihalcea** [comment]
It's in the `joos-mssql` module so everything is related to SQL Server.

All the initial scripts were generated by Hibernate from JPA entities.

**Comment by lukaseder** [comment]
Well, I was confused by the fact that there's the "oracle" directory in the path:
https://github.com/vladmihalcea/high-performance-java-persistence/tree/master/jooq/jooq-mssql/src/test/resources/oracle

**Comment by vladmihalcea** [comment]
That's a mistake indeed.

**Comment by vladmihalcea** [comment]
Fixed by [this commit](https://github.com/vladmihalcea/high-performance-java-persistence/commit/fcb56adb16259e6f4e43ce8e09894c87aa90d348).
