### ISSUE TITLE
CriteriaBulkUpdateDeleteTest.java is referencing a unimplmented method of CriteriaBuilder

### ISSUE THREAD

**Issue by mingqin1** [vladmihalcea/high-performance-java-persistence#21]
Hi: Vlad
Branch-master
CriteriaBulkUpdateDeleteTest.java line 125- lessThanOrEqualTo method in not found in CriteriaBuilder

![untitled](https://user-images.githubusercontent.com/6629272/39649216-dd921d7c-4f99-11e8-809b-c77cc2850bb0.png)

Ming

**Comment by vladmihalcea** [comment]
This is most likely an Eclipse issue. If you run the test from the Maven command line, it works like a charm.

As stated in the README file, I use IntelliJ IDEA, and everything works smoothly. Since I switched to IntelliJ IDEA in 2005, I hadn't ever missed Eclipse.
