### ISSUE TITLE
Compile not working / Oracle JAR requires authorization

### ISSUE THREAD

**Issue by cruftex** [vladmihalcea/high-performance-java-persistence#27]
When I do

````
mvn clean test-compile
````

There is the error:

````
[ERROR] Failed to execute goal on project high-performance-java-persistence: Could not resolve dependencies for project com.vladmihalcea.book:high-performance-java-persistence:pom:1.0-SNAPSHOT: Failed to collect dependencies at com.oracle.jdbc:ojdbc8:jar:12.2.0.1: Failed to read artifact descriptor for com.oracle.jdbc:ojdbc8:jar:12.2.0.1: Could not transfer artifact com.oracle.jdbc:ojdbc8:pom:12.2.0.1 from/to maven.oracle.com (https://maven.oracle.com): Not authorized , ReasonPhrase:Authorization Required. -> [Help 1]
````

When removing the Oracle dependency compilation works.

Probably the Oracle JDBC cannot be obtained from Maven central. One solution would be to put the Oracle dependency in a separate Maven profile.

**Comment by cruftex** [comment]
BTW, the README says exactly:

> The Unit Tests are run against HSQLDB, so no preliminary set-ups are required.

How should I do this?

**Comment by vladmihalcea** [comment]
Just comment the Oracle repository if you don't want to set it up. The tests compile even without the Oracle JDBC Driver.

**Comment by cruftex** [comment]
Sure, that's what I did. However, a lot of other people will have the same experience and need to do the same.

If you like, I can do a PR with a suggestion how to solve this with a Maven profile.
To run the tests with Oracle one would need to do `mvn -Poracle test` then.
In IntelliJ you can enable the profiles in the Maven tool window.

I did something similar here:
https://github.com/cruftex/jsr107-test-zoo/blob/master/pom.xml

If you don't like the idea, that's okay too.

The project is really nice!

Ultimately I would recommend working towards something like:

````
# run the tests with embedded SQL:
mvn test
# run the integration tests with Oracle:
mvn -Poracle verify
# run the integration tests with MySQL:
mvn -Pmysql verify
# run integration tests for performance on PostgreSQL:
mvn -Pperformance,postgresql verify
````

**Comment by vladmihalcea** [comment]
Fixed. The Oracle repo must now be activated explicitly.

**Comment by cruftex** [comment]
@vladmihalcea please mind that you need to move the JDBC driver dependency into the profile as well.

**Comment by vladmihalcea** [comment]
The driver scope is provided so it won't be required during compile. So, it should be just fine.

**Comment by cruftex** [comment]
Scope `provided` means that it is not packaged, since present at the target environment.
It's used for compiling.

If you don't want it in the `compile` scope, then the scope `runtime` is the correct one.
However, `runtime` would be present during running the tests.

**Comment by vladmihalcea** [comment]
You're right. Unfortunately, Maven does not have a `test-runtime` scope, so only moving the dependency to the `oracle` profile does the trick. I pushed a new change to do that. Thanks for the tip.
