### ISSUE TITLE
some dependencies are not in maven central repo

### ISSUE THREAD

**Issue by drahkrub** [vladmihalcea/high-performance-java-persistence#3]
Compilation fails because of
```
[WARNING] The POM for com.oracle:ojdbc7_g:jar:12.1.0.1 is missing, no dependency information available
[WARNING] The POM for com.microsoft.sqlserver:sqljdbc4:jar:4.0 is missing, no dependency information available
```
Would it be possible to add suitable repositories to the base pom.xml?

**Comment by vladmihalcea** [comment]
It's all explained in the [README](https://github.com/vladmihalcea/high-performance-java-persistence/blob/master/README.md). The Oracle and the SQL Server drivers are not available on Maven Central. However, they are needed because I have some tests that rely on some database specific classes (explicit statement caching).

**Comment by drahkrub** [comment]
Sorry for not reading the README - one should not open issues just before end of work... ;-)

Anyway, I think more people would make use of the great stuff you've put in this repo if these "external configurations" would not be required. Maybe splitting it up in a future version (e.g. core-mssql and core-oracle like in jooq)? Providing a pre-configured docker-image on https://hub.docker.com/ would be great, too.

**Comment by vladmihalcea** [comment]
I know what you mean. However, there are some @Parameterized tests that benchmark across various databases and collect the results in one shot. Anyway, it's just 2 libs that you have to add manually. Afterward, you can choose which tests to run and you're fine. Running all tests with `mvn clean install` or `mvn clean test` makes no sense at all. All those tests are meant to be run whenever you want to find out how a specific feature works or behaves.
