### ISSUE TITLE
What is the difference between JSP and servlet?

### ISSUE THREAD

**Issue by riyabhat** [vladmihalcea/high-performance-java-persistence#30]
[JSP and servlet](http://www.exltech.in/java-training.html):

1.Servlet is html in java while  JSP is java in html. 
2.JSP can be compiled into Java Servlets. It's easier to code in JSP than in Java Servlets. 
3.JSP is a webpage scripting language that can generate dynamic content while Servlets are Java programs that are already compiled which also creates dynamic web content.

Please share some more points related to difference between jsp and servlet. 
Visit us:
[http://www.exltech.in/java-training.html](http://www.exltech.in/java-training.html)

**Comment by vladmihalcea** [comment]
Seriously?! Using GitHub issues for spamming is quite lame
