### ISSUE TITLE
Source code does not match book

### ISSUE THREAD

**Issue by klancaster** [vladmihalcea/high-performance-java-persistence#31]
In the book, you say that this repo contains all the source, however that seems not to be the case at all. The code used in the section 10.5.3 is missing, and the text appears to omit some files. Is there a different repo with ALL the source?

**Comment by vladmihalcea** [comment]
The source code is still there. It evolves as well just like Hibernate. There are multiple branches like 5.2, 5.1 as well to match the Hibernate version.

Now, if you refer to the `The @OneToMany alternative` section, the mapping can be found in:

- BidirectionalManyAsOneToManyExtraColumnsTest
- BidirectionalManyAsOneToManyExtraColumnsTestV1
- BidirectionalManyAsOneToManyExtraColumnsTestV2
- BidirectionalManyAsOneToManyOrderColumnTest
- BidirectionalManyAsOneToManyTest
- BidirectionalManyAsOneToManyWithoutEmbeddedIdTest

Enjoy!

**Comment by klancaster** [comment]
Thanks for the quick response! I was not looking in the test directory for the source classes, so sorry for missing that! Great book, and thanks again for the really fast response.

**Comment by vladmihalcea** [comment]
You're welcome. A fast response is exactly what you should expect from a book about High-Performance, right?
