### ISSUE TITLE
Unidirectional OneToOne has @GeneratedValue inside the Post_Details.

### ISSUE THREAD

**Issue by CazacuRadu** [vladmihalcea/high-performance-java-persistence#42]
@vladmihalcea Check the UnidirectionalOneToOne test, you have there the @GeneratedValue even tho in your article you said it should be left out.

**Comment by vladmihalcea** [comment]
If you read the [`@OneToOne` article](https://vladmihalcea.com/the-best-way-to-map-a-onetoone-relationship-with-jpa-and-hibernate/) carefully, you'll see that the `@GeneratedValue` is not needed when sharing the PK, meaning you are using the `@MapsId` annotation. The `UnidirectionalOneToOneTest` does not use `@MapsId`, hence you still need `@GeneratedValue`.
