### ISSUE TITLE
Remove merged hibernate-java8 and hibernate-entitymanager modules

### ISSUE THREAD

**Issue by rajadilipkolli** [vladmihalcea/high-performance-java-persistence#6]
From 5.2.x as these modules are merged with hibernate-core , we should remove from project. If you agree with me I will submit PR

**Comment by vladmihalcea** [comment]
Sure. Send the PR and I'll integrate it.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by rajadilipkolli** [comment]
fixed in https://github.com/vladmihalcea/high-performance-java-persistence/commit/469237ce0b5f1b605778bd9a32479e86644fdc09
