### ISSUE TITLE
methods ambiguous issues on ide

### ISSUE THREAD

**Issue by deepaksorthiya** [vladmihalcea/high-performance-java-persistence#60]
Hi, @vladmihalcea , I imported project to eclipse/intellij , I see the issues on code mention in screenshot.
![java-problem](https://user-images.githubusercontent.com/12553756/89977630-3cfc0100-dc89-11ea-8e87-72faf77cdb5f.JPG)

**Comment by vladmihalcea** [comment]
That's an Eclipse IDE issue. I switched to using IntelliJ IDEA in 2005 and never looked back.

**Comment by deepaksorthiya** [comment]
Okay, Thanks for the reply @vladmihalcea .
