### ISSUE TITLE
Set default JVM language as English for maven on non-english operating systems.

### ISSUE THREAD

**Issue by Kambaa** [vladmihalcea/high-performance-java-persistence#86]
Please add a jvm.config file inside .mvn directory with these arguments `-Duser.country=US -Duser.language=en` that will set JVM to use English as default locale on maven commands.  This will fix localization problems when compiling entities on non-english OS'es as there's an issue with hibernate meta model generator, which makes compiling test classes not possible.

![resim](https://user-images.githubusercontent.com/5601326/229385669-4df18ee4-5689-431c-9ea5-9acc4183e51e.png)

[a stackoverflow issue link](https://stackoverflow.com/questions/57182568/hibernate-jpa-2-metamodel-generator-turkish-char-problem)

**Comment by vladmihalcea** [comment]
@Kambaa Send me a Pull Request with the change proposal, and I'll integrate it.

**Comment by vladmihalcea** [comment]
Closed as I removed the Maven wrapper. The project requires the Maven to be configured externally.
