### ISSUE TITLE
Cannot successfully testCompile, are some classes inside JOOQ missing ?

### ISSUE THREAD

**Issue by Kambaa** [vladmihalcea/high-performance-java-persistence#87]
I think some classes are missing and this makes it fail to compile test classes.

![resim](https://user-images.githubusercontent.com/5601326/229385812-4c9a4c68-b97b-441a-b7fe-fe4764fc0acf.png)

![resim](https://user-images.githubusercontent.com/5601326/229385737-161c1288-58fc-4cf6-a531-213258dd32b2.png)

**Comment by vladmihalcea** [comment]
You can comment out the jOOQ module in the main pom.xml as it's work in progress.

**Comment by vladmihalcea** [comment]
Superseded by #88 88
